### PR TITLE
Latest sources for iOS Push Starter 

### PR DESCRIPTION
**Pull request by AnanthaKrish**

### CODE REVIEW

**Comment by gee4vee** [comment]
Couple more comments plus the ones I made in the files.
- Please remove iosapp.xcodeproj/xcshareddata and iosapp.xcodeproj/xcuserdata folders. We don't want those in source control. And add them to .gitignore.

**Comment by AnanthaKrish** [comment]
@gee4vee Those files are not there in the PR. xcuserdata is added to gitignore.

**Comment by gee4vee** [comment]
@AnanthaKrish please look at the code in the development branch. The following paths are present and need to be removed with this PR so that they are no longer in source control:
- https://github.com/IBM/ios-push-app/blob/development/Podfile.lock
- https://github.com/IBM/ios-push-app/tree/development/iosapp.xcodeproj/xcuserdata/zlozano.xcuserdatad/xcschemes
- https://github.com/IBM/ios-push-app/tree/development/iosapp.xcodeproj/xcshareddata/xcschemes

**Comment by gee4vee** [comment]
@AnanthaKrish please see above comment when you can.

**Comment by AnanthaKrish** [comment]
@gee4vee I have removed the pod lock file. All  the other things will be automatically removed I guess.

**Pull request merged**
